title: BukuKoe.Com Toko Buku Online Libur

email: hello@joecool.com
medium_url: https://www.instagram.com/buku_koe/
github_url: https://www.facebook.com/bukQu
twitter_url: https://bukukoe.com/

exclude: screenshots, LICENSE, README.md
markdown: kramdown
